### ISSUE TITLE
npm version is behind github

### ISSUE THREAD

**Issue by suhajdab** [axelniklasson/node-skanetrafiken#1]
Please push a new version on npm, as the function calls are different and you've added getDepartures.

Thanks for your work btw! :)

**Comment by axelniklasson** [comment]
Hey! Am currently out backpacking in Southeast Asia and will be back in July, so might be a bit hard to push new versions :) will try to do it when I find a computer that works. Glad to hear you like it!

**Comment by axelniklasson** [comment]
Actually managed to publish version 0.0.2 using SSH and my phone - latest commit in master is live in the npm registry now :)
